---
- name: windows update precheck
  hosts: all
  strategy: free
  gather_facts: False
  
  tasks:
    - name: set if the reboot is pending
      win_shell: "{{ lookup('file', 'check_pending_reboot.ps1') }}"
      register: pending_reboot
      
    - name: check if the reboot is pending
      assert:
        that: pending_reboot.stdout_lines[0] == "False"
        msg: 'Server reboot pending is {{ pending_reboot.stdout_lines[0] }}'
  
    - name: Get disk facts
      win_disk_facts:
      
    - name: "Ensure that free disk space on C drive is greater than 10GB"
      vars:
        disk: '{{ ansible_facts.disks[0] }}'
        vol_part: '{{ disk.partitions[1].drive_letter }}'
        minimum_disk_space: 10
        drive_letter: "C"
      assert:
        that: disk.partitions[1].volumes[0].size_remaining/1024|pow(3)|round|int > minimum_disk_space
        msg: 'Remaining disk space has reached {{ disk.partitions[1].volumes[0].size_remaining/1024|pow(3)|round|int }} need 10GB to proceed.'
      when: vol_part ==  drive_letter
        
    - name: Get Windows Update Service Status    
      ansible.windows.win_service_info:
        name: wuauserv
      register: win_service_state
      
    - name: print Windows update Service State
      debug: 
        msg: "{{ win_service_state }}"
      
    - name: "Ensure Windows Update services is runnning"   
      vars:
        running_state: "started"
        service_status: win_service_state.services[0].state
        service_name: win_service_state
      assert:
        that: service_status == running_state
        msg: 'Windows Services "{{ service_name }}" not in running state, please start the service to proceed.'
