---
- name: windows update precheck
  hosts: all
  strategy: free
  gather_facts: False
  
  tasks:
    - name: set if the reboot is pending
      win_shell: "{{ lookup('file', 'check_pending_reboot.ps1') }}"
      register: pending_reboot
      
    - name: check if the reboot is pending
      assert:
        that: 'pending_reboot.stdout_lines[0] == "False"'
        msg: 'Server reboot pending is {{ pending_reboot.stdout_lines[0] }}'
  
    - name: Get disk facts
      win_disk_facts:
      
    - name: "Ensure that free disk space on C drive is greater than 10GB"
      vars:
        disk: '{{ ansible_facts.disks[0] }}'
        vol_part: '{{ disk.partitions[1].drive_letter }}'
        minimum_disk_space: 10
        drive_letter: "C"
      assert:
        that: disk.partitions[1].volumes[0].size_remaining/1024|pow(3)|round|int > minimum_disk_space
        msg: 'Remaining disk space has reached {{ disk.partitions[1].volumes[0].size_remaining/1024|pow(3)|round|int }} need 10GB to proceed.'
      when: vol_part ==  drive_letter
      
    - name: "Get Windows update and BITS services status"
      ansible.windows.win_service:
        name: "{{ item }}"
      register: win_service_state
      with_items:
        - BITS
        - wuauserv
        
    - name: "Ensure Windows update and BITS services are runnning"
      vars:
        service_status: {{ win_service_state }}
        running_state: "running"
      assert:
        that: 
          - win_service_state.name[BITS].state == running_state
          - win_service_state.name[wuauserv].state == running_state
        msg: 'Windows Services {{ win_service_state.name }} are not in running state, please start the service to proceed.'
