---
- name: Windows update precheck
  hosts: all
  strategy: free
  gather_facts: False
  
  tasks:
    - name: check if the reboot is pending
      win_shell: "{{ lookup('file', 'check_pending_reboot.ps1') }}"
      register: pending_reboot
      
    - name: Ensure that server reboot is not pending.
      assert:
        that: pending_reboot.stdout_lines[0] == "False"
        msg: 'Server reboot pending is {{ pending_reboot.stdout_lines[0] }}'
  
    - name: Get disk facts
      win_disk_facts:
      
    - name: "Ensure that free disk space on C drive is greater than 10GB"
      vars:
        disk: '{{ ansible_facts.disks[0] }}'
        vol_part: '{{ disk.partitions[1].drive_letter }}'
        minimum_disk_space: 10
        drive_letter: "C"
      assert:
        that: disk.partitions[1].volumes[0].size_remaining/1024|pow(3)|round|int > minimum_disk_space
        msg: 'Remaining disk space has reached {{ disk.partitions[1].volumes[0].size_remaining/1024|pow(3)|round|int }} need 10GB to proceed.'
      when: vol_part ==  drive_letter
        
    - name: Check Windows Update Service Status    
      win_service:
        name: wuauserv
        state: started
      register: win_service_state
             
    - name: Ensure Windows Update Service is running
      vars:
        service_status: "running"
        service_name: "wuauserv"
      assert:
        that: win_service_state.state == service_status
        msg: 'Windows Service {{ win_service_state.name }} is in {{ win_service_state.state }} state, start the service to proceed.'
      when: win_service_state.name == service_name
