---
- name: Install Updates
  hosts: all
  strategy: free
  ignore_errors: true
  gather_facts: false
  
  tasks:
    - name: Install Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - DefinitionUpdates
          - Updates
        blacklist: "{{ blacklist_package | default(omit, true) }}"
        whitelist: "{{ whitelist_package | default(omit, true) }}"
        state: installed
        reboot: yes
          reboot_timeout: 3600
      register: update_result
    - debug: var=update_result
