---

- name: install updates
  hosts: all
  strategy: free
  gather_facts: False
  
  tasks:
    block:
      - name: Install Windows updates
        win_updates:
          category_names:
            - SecurityUpdates
            - CriticalUpdates
            - UpdateRollups
            - DefinitionUpdates
          blacklist: "{{ blacklist_package | default(omit, true) }}"
          whitelist: "{{ whitelist_package | default(omit, true) }}"
          state: installed
          reboot: yes
        register: update_result
      - debug: var=installed 
