---

- name: install updates
  hosts: all
  strategy: free
  gather_facts: False
  
  tasks:
    - name: Install Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - DefinitionUpdates
        blacklist: "{{ blacklist_package | default(omit, true) }}"
        whitelist: "{{ whitelist_package | default(omit, true) }}"
        state: installed
        reboot: yes
      when: found_update_count > 0
      register: update_result
    - debug: var=installed 
