---
category: ['Updates'] #good example of single item of list [SecurityUpdates, 'Updates'] for multiple
disk: '{{ ansible_facts.disks[0] }}'
email_account: "13cdc618117f13"
email_account_password: "cd5848a59223e6"
sendto_email: "Ansible Dev <13cdc618117f13>"
