---
category: ['Updates'] #good example of single item of list [SecurityUpdates, 'Updates'] for multiple
email_account: "ansible.dev1@gmail.com"
email_password: "12QWaszx!"
sendto_email: "Ansible Dev1 <ansible.dev1@gmail.com>"
