---
category: ['Updates'] #good example of single item of list [SecurityUpdates, 'Updates'] for multiple
email_account: "snehal.p.patel@global.ntt"
sendto_email: "Snehal Patel <snehal.p.patel@global.ntt>"

