---
category: ['Updates'] #good example of single item of list [SecurityUpdates, 'Updates'] for multiple
gmail_account: "ansible.dev1@gmail.com"
gmail_account_password: "12QWaszx!"
sendto_email: "Ansible Dev <ansible.dev1@gmail.com>"

